version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app:delegated  # Mount entire monorepo
      - /app/node_modules
      - /app/apps/web/node_modules
      - /app/packages/eslint-config/node_modules
      - /app/packages/typescript-config/node_modules
      - /app/packages/ui/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VIRTUAL_HOST=my-domain.local
      - VIRTUAL_PORT=3000
    networks:
      - app-network
      - nginx-proxy

      
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - nginx-proxy

networks:
  app-network:
  nginx-proxy:
